/* ==========================================================================
   AWS SERVERLESS NOTES MANAGER — APPLICATION LOGIC
   Vanilla JavaScript, no frameworks.
   NOTE: All API endpoints, fetch calls, request bodies and response handling
   are unchanged from the original implementation. Only presentational
   markup generated by JS (e.g. the status badge below) was added.
   ========================================================================== */

/* ==========================================================================
   CONFIGURATION
   Change ONLY this value to point the app at your AWS API Gateway stage.
   Example: "https://abc123xyz.execute-api.ap-south-1.amazonaws.com/prod"
   ========================================================================== */
const API_BASE_URL = "https://hmaue362a4.execute-api.ap-south-1.amazonaws.com";

/* ---------------------------- App State ---------------------------- */
const state = {
  totalRequests: 0,
  successRequests: 0,
  failedRequests: 0,
  notesSaved: 0,
  history: [], // { method, filename, success, time, durationMs }
};

/* ---------------------------- DOM References ---------------------------- */
const dom = {
  // Top nav
  statusDot: document.getElementById("statusDot"),
  statusText: document.getElementById("statusText"),
  clock: document.getElementById("clock"),

  // Create form
  createForm: document.getElementById("createForm"),
  filenameInput: document.getElementById("filenameInput"),
  filenameError: document.getElementById("filenameError"),
  contentInput: document.getElementById("contentInput"),
  contentError: document.getElementById("contentError"),
  charCounter: document.getElementById("charCounter"),
  saveBtn: document.getElementById("saveBtn"),

  // Read form
  readForm: document.getElementById("readForm"),
  readFilenameInput: document.getElementById("readFilenameInput"),
  readFilenameError: document.getElementById("readFilenameError"),
  readBtn: document.getElementById("readBtn"),
  readResultArea: document.getElementById("readResultArea"),
  readEmptyState: document.getElementById("readEmptyState"),

  // Stats
  statTotal: document.getElementById("statTotal"),
  statSuccess: document.getElementById("statSuccess"),
  statFailed: document.getElementById("statFailed"),
  statSaved: document.getElementById("statSaved"),

  // History
  historyList: document.getElementById("historyList"),
  historyEmpty: document.getElementById("historyEmpty"),
  historyRowTemplate: document.getElementById("historyRowTemplate"),
  clearHistoryBtn: document.getElementById("clearHistoryBtn"),

  // Toasts
  toastContainer: document.getElementById("toastContainer"),
};

/* ==========================================================================
   INITIALIZATION
   ========================================================================== */
function init() {
  startClock();
  checkConnection();
  bindEvents();
  autoResizeTextarea(dom.contentInput);
}

function bindEvents() {
  dom.createForm.addEventListener("submit", handleSaveSubmit);
  dom.readForm.addEventListener("submit", handleReadSubmit);
  dom.contentInput.addEventListener("input", handleContentInput);
  dom.clearHistoryBtn.addEventListener("click", clearHistory);

  // Keyboard shortcut: Ctrl/Cmd + Enter saves the note from anywhere in the create card
  document.addEventListener("keydown", (event) => {
    const isSaveShortcut = (event.ctrlKey || event.metaKey) && event.key === "Enter";
    if (isSaveShortcut) {
      const activeElement = document.activeElement;
      const isInsideCreateForm = dom.createForm.contains(activeElement);
      if (isInsideCreateForm || activeElement === document.body) {
        event.preventDefault();
        dom.createForm.requestSubmit();
      }
    }
  });
}

/* ==========================================================================
   CLOCK
   ========================================================================== */
function startClock() {
  const update = () => {
    const now = new Date();
    const dateStr = now.toLocaleDateString(undefined, {
      weekday: "short",
      month: "short",
      day: "numeric",
    });
    const timeStr = now.toLocaleTimeString(undefined, { hour12: true });
    dom.clock.textContent = `${dateStr} · ${timeStr}`;
  };
  update();
  setInterval(update, 1000);
}

/* ==========================================================================
   CONNECTION STATUS
   ========================================================================== */
function checkConnection() {
  if (!API_BASE_URL) {
    setConnectionStatus("offline", "API_BASE_URL not configured");
    return;
  }
  setConnectionStatus("online", "Endpoint configured");
}

function setConnectionStatus(mode, label) {
  dom.statusDot.classList.remove("status-dot--online", "status-dot--offline");
  dom.statusDot.classList.add(mode === "online" ? "status-dot--online" : "status-dot--offline");
  dom.statusText.textContent = label;
}

/* ==========================================================================
   VALIDATION
   ========================================================================== */
function validateInput(value, fieldErrorEl, message) {
  const trimmed = (value || "").trim();
  if (!trimmed) {
    fieldErrorEl.textContent = message;
    return false;
  }
  fieldErrorEl.textContent = "";
  return true;
}

function clearFieldError(inputEl, errorEl) {
  inputEl.classList.remove("input--invalid");
  errorEl.textContent = "";
}

/* ==========================================================================
   CREATE NOTE — POST /note
   ========================================================================== */
async function handleSaveSubmit(event) {
  event.preventDefault();
  clearFieldError(dom.filenameInput, dom.filenameError);
  clearFieldError(dom.contentInput, dom.contentError);

  const filename = dom.filenameInput.value.trim();
  const content = dom.contentInput.value.trim();

  const filenameValid = validateInput(filename, dom.filenameError, "Filename is required.");
  const contentValid = validateInput(content, dom.contentError, "Note content cannot be empty.");

  if (!filenameValid) dom.filenameInput.classList.add("input--invalid");
  if (!contentValid) dom.contentInput.classList.add("input--invalid");
  if (!filenameValid || !contentValid) return;

  await saveNote(filename, content);
}

async function saveNote(filename, content) {
  showLoader(dom.saveBtn);
  const startTime = performance.now();

  try {
    if (!API_BASE_URL) {
      throw new Error("API_BASE_URL is not configured. Set it in script.js to connect your AWS API Gateway endpoint.");
    }

    const response = await fetch(`${API_BASE_URL}/note`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ filename, content }),
    });

    const durationMs = Math.round(performance.now() - startTime);

    if (!response.ok) {
      const errorBody = await safeParseJson(response);
      throw new Error(errorBody?.message || `Request failed with status ${response.status}`);
    }

    addHistory("POST", filename, true, durationMs);
    updateStatistics({ success: true, saved: true });
    showToast("success", `Note "${filename}" saved successfully.`);

    dom.createForm.reset();
    handleContentInput();
  } catch (error) {
    const durationMs = Math.round(performance.now() - startTime);
    addHistory("POST", filename, false, durationMs);
    updateStatistics({ success: false });
    showError(error.message || "Failed to save note.");
  } finally {
    hideLoader(dom.saveBtn);
  }
}

/* ==========================================================================
   READ NOTE — GET /note?filename=...
   ========================================================================== */
async function handleReadSubmit(event) {
  event.preventDefault();
  clearFieldError(dom.readFilenameInput, dom.readFilenameError);

  const filename = dom.readFilenameInput.value.trim();
  const filenameValid = validateInput(filename, dom.readFilenameError, "Filename is required.");

  if (!filenameValid) {
    dom.readFilenameInput.classList.add("input--invalid");
    return;
  }

  await readNote(filename);
}

async function readNote(filename) {
  showLoader(dom.readBtn);
  const startTime = performance.now();

  try {
    if (!API_BASE_URL) {
      throw new Error("API_BASE_URL is not configured. Set it in script.js to connect your AWS API Gateway endpoint.");
    }

    const url = `${API_BASE_URL}/note?filename=${encodeURIComponent(filename)}`;
    const response = await fetch(url, { method: "GET" });
    const durationMs = Math.round(performance.now() - startTime);

    if (!response.ok) {
      const errorBody = await safeParseJson(response);
      throw new Error(errorBody?.message || `Request failed with status ${response.status}`);
    }

    const data = await response.json();
    addHistory("GET", filename, true, durationMs);
    updateStatistics({ success: true });
    showToast("success", `Note "${filename}" loaded.`);
    renderReadResult(filename, data.content ?? "", new Date());
  } catch (error) {
    const durationMs = Math.round(performance.now() - startTime);
    addHistory("GET", filename, false, durationMs);
    updateStatistics({ success: false });
    showError(error.message || "Failed to read note.");
  } finally {
    hideLoader(dom.readBtn);
  }
}

/* ---------------------------- Read Result Rendering ---------------------------- */
function renderReadResult(filename, content, timestamp) {
  dom.readResultArea.innerHTML = "";

  const card = document.createElement("div");
  card.className = "result-card";
  card.innerHTML = `
    <div class="result-card__header">
      <span class="result-card__filename">${escapeHtml(filename)}</span>
      <span class="result-card__badge">Loaded</span>
    </div>
    <div class="result-card__content"></div>
    <div class="result-card__footer">
      <span class="result-card__timestamp">${timestamp.toLocaleString()}</span>
      <div class="result-card__actions">
        <button type="button" class="btn btn--ghost" data-action="copy">Copy content</button>
        <button type="button" class="btn btn--ghost" data-action="download">Download note</button>
      </div>
    </div>
  `;

  // Set text content separately to avoid HTML injection from note body
  card.querySelector(".result-card__content").textContent = content;

  card.querySelector('[data-action="copy"]').addEventListener("click", () => copyToClipboard(content));
  card.querySelector('[data-action="download"]').addEventListener("click", () => downloadNote(filename, content));

  dom.readResultArea.appendChild(card);
}

async function copyToClipboard(text) {
  try {
    await navigator.clipboard.writeText(text);
    showToast("success", "Content copied to clipboard.");
  } catch {
    showToast("warning", "Could not copy automatically. Please copy manually.");
  }
}

function downloadNote(filename, content) {
  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename || "note.txt";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/* ==========================================================================
   LOADING STATE HELPERS
   ========================================================================== */
function showLoader(buttonEl) {
  buttonEl.classList.add("is-loading");
  buttonEl.disabled = true;
}

function hideLoader(buttonEl) {
  buttonEl.classList.remove("is-loading");
  buttonEl.disabled = false;
}

/* ==========================================================================
   STATISTICS — animated counters
   ========================================================================== */
function updateStatistics({ success, saved = false }) {
  state.totalRequests += 1;
  if (success) state.successRequests += 1;
  else state.failedRequests += 1;
  if (saved) state.notesSaved += 1;

  animateCounter(dom.statTotal, state.totalRequests);
  animateCounter(dom.statSuccess, state.successRequests);
  animateCounter(dom.statFailed, state.failedRequests);
  animateCounter(dom.statSaved, state.notesSaved);
}

function animateCounter(el, targetValue) {
  const startValue = parseInt(el.dataset.count, 10) || 0;
  if (startValue === targetValue) return;

  const duration = 400;
  const startTime = performance.now();

  function step(now) {
    const progress = Math.min((now - startTime) / duration, 1);
    const current = Math.round(startValue + (targetValue - startValue) * progress);
    el.textContent = current;
    if (progress < 1) {
      requestAnimationFrame(step);
    } else {
      el.dataset.count = targetValue;
    }
  }
  requestAnimationFrame(step);
}

/* ==========================================================================
   REQUEST HISTORY PANEL
   ========================================================================== */
function addHistory(method, filename, success, durationMs) {
  const entry = {
    method,
    filename,
    success,
    time: new Date().toLocaleTimeString(undefined, { hour12: true }),
    durationMs,
  };
  state.history.unshift(entry);

  if (dom.historyEmpty) {
    dom.historyEmpty.remove();
    dom.historyEmpty = null;
  }

  const row = dom.historyRowTemplate.content.firstElementChild.cloneNode(true);
  const methodEl = row.querySelector(".history-row__method");
  methodEl.textContent = method;
  methodEl.classList.add(method === "POST" ? "method--post" : "method--get");

  row.querySelector(".history-row__filename").textContent = entry.filename;

  const statusEl = row.querySelector(".history-row__status");
  statusEl.textContent = success ? "Success" : "Error";
  statusEl.classList.add(success ? "status--success" : "status--error");

  row.querySelector(".history-row__time").textContent = entry.time;
  row.querySelector(".history-row__duration").textContent = `${durationMs} ms`;

  dom.historyList.prepend(row);
}

function clearHistory() {
  state.history = [];
  dom.historyList.innerHTML = "";
  const emptyDiv = document.createElement("div");
  emptyDiv.className = "history-empty";
  emptyDiv.id = "historyEmpty";
  emptyDiv.innerHTML = `<p>No requests yet.</p><p class="history-empty__sub">API calls will appear here in real time.</p>`;
  dom.historyList.appendChild(emptyDiv);
  dom.historyEmpty = emptyDiv;
}

/* ==========================================================================
   TOAST NOTIFICATIONS
   ========================================================================== */
const TOAST_ICONS = { success: "✓", error: "✕", warning: "!" };
const TOAST_DURATION_MS = 4000;

function showToast(type, message) {
  const toast = document.createElement("div");
  toast.className = `toast toast--${type}`;
  toast.setAttribute("role", "status");
  toast.innerHTML = `
    <span class="toast__icon">${TOAST_ICONS[type] || "•"}</span>
    <span class="toast__text"></span>
  `;
  toast.querySelector(".toast__text").textContent = message;

  dom.toastContainer.appendChild(toast);

  setTimeout(() => {
    toast.classList.add("is-leaving");
    setTimeout(() => toast.remove(), 200);
  }, TOAST_DURATION_MS);
}

function showError(message) {
  showToast("error", message);
}

/* ==========================================================================
   MISC UI HELPERS
   ========================================================================== */
function handleContentInput() {
  const length = dom.contentInput.value.length;
  dom.charCounter.textContent = `${length} character${length === 1 ? "" : "s"}`;
  autoResizeTextarea(dom.contentInput);
}

function autoResizeTextarea(textareaEl) {
  textareaEl.style.height = "auto";
  textareaEl.style.height = `${Math.min(textareaEl.scrollHeight, 400)}px`;
}

function escapeHtml(value) {
  const div = document.createElement("div");
  div.textContent = value;
  return div.innerHTML;
}

async function safeParseJson(response) {
  try {
    return await response.json();
  } catch {
    return null;
  }
}

/* ==========================================================================
   BOOTSTRAP
   ========================================================================== */
document.addEventListener("DOMContentLoaded", init);